#!/bin/bash

# Generate both an index.en.html and index.es.html from index.html using translation.es

base="$1"

if [ -z "$base" ]; then
  printf "Please base the URL base directory as first argument, e.g. '/mexcla'.\n"
  exit 1
fi

# Unset base if it's the root directory to avoid //
[ "$base" = "/" ] && base=

# Simply eliminate the pipes for the english version.
cat index.base | tr -d '|' > index.en.html
cp index.base index.es.html
# Replace strings in spanish version.
cat translation.es | grep -v ^# | while read line; do
  en=$(echo "$line" | cut -d= -f1 | tr -d '|')
  es=$(echo "$line" | cut -d= -f2)
  perl -p -i -e "s#$en#$es#;" index.es.html
done

temp=$(mktemp)
# Now remove pipes from spanish file
cat index.es.html | tr -d '|' > "$temp"
mv "$temp" index.es.html

# Optionally pass base as first argument (if you are running this version in a 
# subdirectory), e.g.: ./generate-pages "/mexcla"
perl -p -i -e "s#{base}#$base#;" index.en.html
perl -p -i -e "s#{base}#$base#;" index.es.html

